services:
  backend:
    image: ghcr.io/thenerdshub/nerdhub-backend:latest
    ports:
      - "${BACKEND_PORT}:80"
    depends_on:
      - mongo
    environment:
      - ASPNETCORE_URLS=http://+:80 # Set this port to the same as the internal port
      - BACKEND_MONGO_URI=${BACKEND_MONGO_URI}
      - BACKEND_STEAM_API_KEY=${BACKEND_STEAM_API_KEY}
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
    networks:
      nerdhub-network:
        ipv4_address: 172.20.0.2

  frontend:
    image: ghcr.io/thenerdshub/nerdhub-frontend:latest
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
      - imgproxy
    environment:
      - API_URL_EXTERNAL=${API_URL_EXTERNAL}
    networks:
      nerdhub-network:
        ipv4_address: 172.20.0.3

  discordbot:
    image: ghcr.io/thenerdshub/nerdhub-discord:latest
    depends_on:
      - mongo
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - API_URL_INTERNAL=${API_URL_INTERNAL}
    networks:
      nerdhub-network:
        ipv4_address: 172.20.0.4

  imgproxy:
    image: ghcr.io/imgproxy/imgproxy:latest
    ports:
      - "${IMGPROXY_PORT:-8080}:8080"
    environment:
      - IMGPROXY_ALLOWED_SOURCES=https://*.steamstatic.com/,https://*.akamaihd.net/
      - IMGPROXY_MAX_SRC_RESOLUTION=100
      - IMGPROXY_CACHE_TTL=31536000
      - IMGPROXY_USE_ETAG=true
      - IMGPROXY_AVIF_QUALITY=65
      - IMGPROXY_WEBP_QUALITY=80
      - IMGPROXY_JPEG_QUALITY=80
      - IMGPROXY_FREE_MEMORY_INTERVAL=30
      - IMGPROXY_MALLOC=tcmalloc
    networks:
      nerdhub-network:
        ipv4_address: 172.20.0.6

  mongo:
    image: mongo
    ports:
      - "${MONGODB_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      nerdhub-network:
        ipv4_address: 172.20.0.5

#postgres:
#  image: postgres:latest
#  ports:
#    - "${POSTGRES_PORT}:5432"
#  volumes:
#    - postgres-data:/var/lib/postgresql/data
#  networks:
#    nerdhub-network:
#      ipv4_address: 172.20.0.6
#
#  keycloak:
#    image: quay.io/keycloak/keycloak:latest
#    command: 
#      - start-dev
#    ports:
#      - "${KEYCLOAK_PORT}:8080"
#   networks:
#     nerdhub-network:
#       ipv4_address: 172.20.0.7

volumes:
  mongo-data:
# postgres-data:

networks:
  nerdhub-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16