FROM node:22-alpine
WORKDIR /app

# Install git
RUN apk add --no-cache git

# Clone the Discord bot repository
RUN git clone https://github.com/TheNerdsHub/NerdHub-Discord.git .
WORKDIR /app/NerdHub-Discord

# Install dependencies
RUN npm install

# Start the bot
CMD ["node", "index.js"]