services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "${BACKEND_PORT}:80"
    depends_on:
      - mongo
    env_file:
      - stack.env
    networks:
      - nerdhub-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "${FRONTEND_PORT}:80"
    env_file:
      - stack.env
    networks:
      - nerdhub-network

  discordbot:
    build:
      context: .
      dockerfile: Dockerfile.discordbot
    depends_on:
      - mongo
    env_file:
      - stack.env
    networks:
      - nerdhub-network

  mongo:
    image: mongo
    ports:
      - "${MONGODB_PORT}:27017"
    env_file:
      - stack.env
    volumes:
      - mongo-data:/data/db
    networks:
      - nerdhub-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - nerdhub-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    ports:
      - "${KEYCLOAK_PORT}:8080"
    env_file:
      - stack.env
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
    depends_on:
      - postgres
    networks:
      - nerdhub-network

volumes:
  mongo-data:
  postgres-data:

networks:
  nerdhub-network:
    driver: bridge