services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "${BACKEND_PORT}:80"
    depends_on:
      - mongo
    env_file:
      - stack.env
    networks:
      - nerdhub-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "${FRONTEND_PORT}:80"
    env_file:
      - stack.env
    networks:
      - nerdhub-network

  discordbot:
    build:
      context: .
      dockerfile: Dockerfile.discordbot
    depends_on:
      - mongo
    env_file:
      - stack.env
    networks:
      - nerdhub-network

  mongo:
    image: mongo
    ports:
      - "${MONGODB_PORT}:27017"
    env_file:
      - stack.env
    volumes:
      - mongo-data:/data/db
    networks:
      - nerdhub-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "${KEYCLOAK_PORT}:8080"
    env_file:
      - stack.env
    networks:
      - nerdhub-network

volumes:
  mongo-data:

networks:
  nerdhub-network:
    driver: bridge