services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "${BACKEND_PORT}:80"
    depends_on:
      - mongo
    env_file:
      - stack.env
    networks:
      nerdhub-network:
        ipv4_address: 172.20.0.2

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "${FRONTEND_PORT}:80"
    env_file:
      - stack.env
    networks:
      nerdhub-network:
        ipv4_address: 172.20.0.3

  discordbot:
    build:
      context: .
      dockerfile: Dockerfile.discordbot
    depends_on:
      - mongo
    env_file:
      - stack.env
    networks:
      nerdhub-network:
        ipv4_address: 172.20.0.4

  mongo:
    image: mongo
    ports:
      - "${MONGODB_PORT}:27017"
    env_file:
      - stack.env
    volumes:
      - mongo-data:/data/db
    networks:
      nerdhub-network:
        ipv4_address: 172.20.0.5

  postgres:
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - stack.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      nerdhub-network:
        ipv4_address: 172.20.0.6

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: 
      - start-dev
    ports:
      - "${KEYCLOAK_PORT}:8080"
    env_file:
      - stack.env
    depends_on:
      - postgres
    networks:
      nerdhub-network:
        ipv4_address: 172.20.0.7

volumes:
  mongo-data:
  postgres-data:

networks:
  nerdhub-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
