FROM node:18
WORKDIR /app

# Clone the Discord bot repository
RUN git clone https://github.com/TheNerdsHub/NerdHub-DiscordBot.git .
WORKDIR /app/NerdHub-DiscordBot

# Install dependencies
COPY package*.json ./
RUN npm install
COPY . .

# Start the bot
CMD ["node", "bot.js"]